### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by wlwyrick** [robinraju/release-downloader#534] opened 2022-10-12 14:32 UTC
**Describe the bug**
When run, the following warning is received. Would you make the suggested change? Thanks!
"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."

**To Reproduce**
1. Run the action

**Expected behavior**
No warning.

**Screenshots**

**Action Environment (please complete the following information):**
 - OS:  linux

**Additional context**

**Comment by robinraju** [comment] 2022-10-17 19:14
@wlwyrick I couldn't reproduce the warning you've reported. Here is a recent run of this action: https://github.com/robinraju/release-downloader/actions/runs/3267845900/jobs/5373546975

Could you please add a screenshot or link to your failed run (if its public)

**Comment by wlwyrick** [comment] 2022-10-17 22:14
The repo is private, so I can't send a link. 

![image](https://user-images.githubusercontent.com/79112179/196293197-97cc7db2-5282-41af-aeed-1ab74814d761.png)

I got this warning multiple times and replaced all the set-output commands in the workflow, but still got one remaining. Since the workflow only uses one action, I thought this was what was causing the warning. 

If you don't use set-output, then it must be caused by something else.

**Comment by jonz94** [comment] 2022-10-18 00:16
Hi there,

I made a minimal project to reproduce this issue. (https://github.com/jonz94/release-downloader-issue/actions/runs/3269517029/jobs/5377102326#step:3:16)

And I also found that the issue can be fixed by upgrading `@actions/core` package to latest v1.10.0 version.

**Closed** 2022-10-18 16:40 UTC

**Comment by robinraju** [comment] 2022-10-18 16:48
The pr from @jonz94 is merged. You may test it using the commit hash.

```
- uses: robinraju/release-downloader@62d3e983c99c16718304fb1a69553f01b84b0d40
  with:
    latest: true
    fileName: "foo.zip"
```
