### ISSUE TITLE
Getting 400 on all downloads

### ISSUE THREAD

**Issue by FalconerTC** [robinraju/release-downloader#333] opened 2021-12-02 17:46 UTC
**Describe the bug**
As of this morning, all downloads using this action are giving a 400

eg
```
Fetching latest release for repo RentTheRunway/<repo>
Downloading file: <tool>-linux-amd64.tar.gz to: /runner/_work/<runner>
Error: Unexpected response: 400
```

Curious if anyone else just started seeing this? Maybe the API changed today?

**To Reproduce**
1. Execute a download against a private repo

**Expected behavior**
It should successfully download the artifact

**Action Environment (please complete the following information):**
 - OS: ubuntu (self-hosted)

**Additional context**
I'm running with the following

```
      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "RentTheRunway/<repo>"
          latest: true
          fileName: "<file>-linux-amd64.tar.gz"
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
```

**Comment by FalconerTC** [comment] 2021-12-02 17:47
Sorry, this is probably an expired token

**Comment by FalconerTC** [comment] 2021-12-02 17:55
Actually, this doesn't seem to be related to a token expiration

**Comment by lesfadv** [comment] 2021-12-02 20:10
We are having the same issue. This has broken our CI/CD pipeline.

**Comment by FalconerTC** [comment] 2021-12-02 20:34
Did some more digging here and opened a Github ticket to get more info from them on what changed. The problem is authentication headers being passed on redirect requests. The HTTP library being used by this action (`typed-rest-client`) strips authentication headers for some auth types but not when set as a general header, as is done in this action. I made an issue there https://github.com/microsoft/typed-rest-client/issues/302.

I'm not sure if there's a flag or something that can be set here to prevent those headers from being passed along on redirect.

**Comment by smistad** [comment] 2021-12-03 07:34
Same issue here

**Comment by robinraju** [comment] 2021-12-03 09:31
As @FalconerTC described, this is caused by the current `rest-client` used in this action sending the `Authorization` header when following a redirect request. Looks like a change in behaviour of [gh-api ](https://docs.github.com/en/rest/reference/repos#get-a-release-asset). It now sends a `302` and the location of the file to be downloaded. 
> I may be able to look into this issue later today/this weekend only. I would replace the HTTP client library if a workaround for this can't be found.

**Comment by valentjn** [comment] 2021-12-03 17:15
Not sure if relevant or off-topic, but [using Python 3's `urllib.request`](https://github.com/valentjn/vscode-ltex/blob/d1c7cb2d31e2e4f4b8549d49993b29322902bae1/tools/common.py#L58-L76) produces the same error when trying to download a release from GitHub with an `Authorization` header (this breaks my GitHub Actions workflows). I'm not using the action from this repo or its REST client. Maybe GitHub needs to fix this in their API, but I'm not sure where to report this.

**Comment by robinraju** [comment] 2021-12-04 23:54
Hey everyone, thanks for your inputs. I just merged a fix for this issue. It runs fine now. You can check the test logs here 
https://github.com/robinraju/release-downloader/runs/4419579702?check_suite_focus=true

You may try it out from the main branch as follows.
```
 - uses: robinraju/release-downloader@main
```
I'll create a new release once someone confirms if it works as expected.

**Comment by smistad** [comment] 2021-12-05 07:20
@robinraju It works for me 👍👍 Thanks

**Comment by ndobbs** [comment] 2021-12-07 01:47
> Hey everyone, thanks for your inputs. I just merged a fix for this issue. It runs fine now. You can check the test logs here https://github.com/robinraju/release-downloader/runs/4419579702?check_suite_focus=true
> 
> You may try it out from the main branch as follows.
> 
> ```
>  - uses: robinraju/release-downloader@main
> ```
> 
> I'll create a new release once someone confirms if it works as expected.

This fixed our builds as well! Thanks a ton!

**Comment by BevanR** [comment] 2021-12-07 02:20
Ditto. Could we get a release please, so that we don't need to use `@main`?

**Comment by robinraju** [comment] 2021-12-07 08:55
Published a new release https://github.com/robinraju/release-downloader/releases/tag/v1.3

You can use the latest version with a fix for this issue.
```
- name: release-downloader
  uses: robinraju/release-downloader@v1.3

```

Closing this issue with the resolution as described above.

**Closed by robinraju** 2021-12-07 08:55 UTC
